stages:
- check

pre-commit:
  stage: check
  image: python:3
  before_script:
  - pip install pre-commit
  script:
  - TMP_MSG_FILE="$(mktemp)"
  - git log -1 --pretty=%B > "${TMP_MSG_FILE}"
  - pre-commit run --all-files --color=always --hook-stage commit &&
    pre-commit run --all-files --color=always --hook-stage commit-msg --commit-msg-filename "${TMP_MSG_FILE}" &&
    pre-commit run --all-files --color=always --hook-stage post-commit || {
      >&2 echo "pre-commit checks failed. Please consider installing pre-commit";
      >&2 echo "hooks in your local Git clone by running \`make git-hooks-install\`.";
      exit 1;
    }
